service: config

frameworkVersion: ">=1.28.0 <=3.38.0"

provider:
  name: aws
  runtime: go1.x
  region: "eu-central-1"
  environment:
    REGION: "eu-central-1"

  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "dynamodb:Query"
        - "dynamodb:Scan"
        - "dynamodb:GetItem"
        - "dynamodb:PutItem"
        - "dynamodb:UpdateItem"
        - "dynamodb:DeleteItem"
        - "dynamodb:BatchWriteItem"
      Resource:
        - "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/ConfigItems"

package:
  patterns:
    - '!./**'
    - './bin/**'

functions:
  getconfig:
    handler: bin/getconfig
    events:
      - http:
          path: /config/{key}
          method: GET
          cors: true
  putconfig:
    handler: bin/putconfig
    events:
      - http:
          path: /config
          method: POST
          cors: true

resources:
  Resources:
    ConfigItemsTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Delete
      Properties:
        AttributeDefinitions:
          - AttributeName: Key
            AttributeType: S
        KeySchema:
          - AttributeName: Key
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ConfigItems