service: config

frameworkVersion: ">=1.28.0 <=3.38.0"

provider:
  name: aws
  runtime: go1.x
  region: "eu-central-1"

package:
  exclude:
    - ./**
  include:
    - ./bin/**

functions:
  jobs:
    handler: bin/getconfig
    events:
      - http:
          path: /config
          method: GET
          cors: true